### ISSUE TITLE
taskflow cap is blocking the usage of newer versions of taskflow in openstack

### ISSUE THREAD

**Issue by prometheanfire** [powervm/pypowervm#12]
see http://logs.openstack.org/29/661429/4/check/requirements-tox-py27-check-uc/293a0e7/job-output.txt.gz#_2019-05-27_00_37_29_789938 while the logs last

```
2019-05-27 00:37:29.789671 | ubuntu-bionic | Checking upper-constraints.txt
2019-05-27 00:37:29.789743 | ubuntu-bionic | Checking conflicts for pypowervm:
2019-05-27 00:37:29.789938 | ubuntu-bionic | ContextualVersionConflict: (taskflow 3.6.0 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/lib/python2.7/site-packages), Requirement.parse('taskflow<3.2.0,>=2.16.0'), set(['pypowervm']))
2019-05-27 00:37:29.790000 | ubuntu-bionic | Traceback (most recent call last):
2019-05-27 00:37:29.790124 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/openstack_requirements/cmds/check_conflicts.py", line 59, in main
2019-05-27 00:37:29.790200 | ubuntu-bionic |     pkg_resources.require(name)
2019-05-27 00:37:29.790354 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
2019-05-27 00:37:29.790434 | ubuntu-bionic |     needed = self.resolve(parse_requirements(requirements))
2019-05-27 00:37:29.790586 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
2019-05-27 00:37:29.790668 | ubuntu-bionic |     raise VersionConflict(dist, req).with_context(dependent_req)
2019-05-27 00:37:29.790879 | ubuntu-bionic | ContextualVersionConflict: (taskflow 3.6.0 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/lib/python2.7/site-packages), Requirement.parse('taskflow<3.2.0,>=2.16.0'), set(['pypowervm']))
2019-05-27 00:37:29.829920 | ubuntu-bionic | ERROR: InvocationError for command /home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/bin/check-conflicts upper-constraints.txt upper-constraints-xfails.txt (exited with code 1)
2019-05-27 00:37:29.830020 | ubuntu-bionic | py27-check-uc finish: run-test  after 4.88 seconds
```

**Comment by prometheanfire** [comment]
actually, it looks like pypowervm will be held back because it has a cap on taskflow now.

https://github.com/powervm/pypowervm/commit/5dc88d1d0372cf1d5094a01d7525b255cb7420d7

**Comment by prometheanfire** [comment]
any update on this?

**Comment by 2uasimojo** [comment]
@prometheanfire I'm still getting notified on this repo, but I no longer have the access/ability to do anything about these issues.

The powervm team, such as it is, conducts meetings in #openstack-powervm [1]. That looks like it's probably an inconvenient time for you, but it may give you a clue who to stalk in that channel.

You might also get some mileage by emailing the powervm CI address, listed here [2]. Assuming there are still warm bodies at the other end, they should be (or at least be able to connect you to) the same people who maintain pypowervm.

Good luck,
efried

[1] http://eavesdrop.openstack.org/meetings/openstack_powervm/2019/openstack_powervm.2019-07-10-09.04.log.html
[2] https://wiki.openstack.org/wiki/ThirdPartySystems/IBM_PowerVM_CI
